version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
        - ./:/code
    ports:
        - "8080:8080"
    environment:
        - CHOKIDAR_USEPOLLING=true
    entrypoint: ./yarn-start.sh
